data:
  root_dir: /tmp
  cache_dir: /tmp
  cache_name: tmp
  num_points: 3500
  num_object_points: 1024
  cam_coord: false
  num_rotations: 64
  grid_resolution: 0.01
  jitter_scale: 0.0
  contact_radius: 0.005
  dist_above_table: 0.002
  robot_prob: 1.0
  random_seed: 0
  min_grasps_gen_th: 5
  rotation_augmentation: true
  add_depth_noise: false
  downsample_points: true
  downsample_to_fixed_batch_size: false
  dataset_cls: ObjectPickDataset
  load_patch: false
  load_onehot_vec: false
  load_discriminator_dataset: false
  patch_width: 256
  prob_point_cloud: 0.5
  object_root_dir: /tmp
  grasp_root_dir: /tmp
  num_grasps_per_object: 500
  load_contact: false
  discriminator_ratio:
  - 0.5
  - 0.2
  - 0.25
  - 0.05
  - 0.0
  visualize_batch: false
  onpolicy_dataset_json_dir: null
  onpolicy_dataset_h5_dir: null
  onpolicy_dataset_name: null
  render_redundancy: 3
  cache_save_freq: 5000
  single_gripper: null
  loading_mode: lazy
  alternative_json_file_path: null
diffusion:
  object_backbone: ptv3vanilla
  gripper_backbone: sweep_volume_v2
  pointnet_version: v2
  checkpoint_object_encoder_pretrained: null
  num_embed_dim: 256
  num_object_dim: 512
  num_gripper_dim: 512
  diffusion_embed_dim: 512
  image_size: 256
  num_diffusion_iters: 20
  num_diffusion_iters_eval: 20
  compositional_schedular: true
  loss_pointmatching: false
  loss_l1_pos: true
  loss_l1_rot: true
  grasp_repr: r3_so3
  kappa: 3.27
  clip_sample: true
  beta_schedule: squaredcos_cap_v2
  npn_architecture: ffn
  attention: cat_attn
  pose_repr: mlp
  num_grasps_per_object: 100
  ptv3:
    grid_size: 0.01
  ptv3vanilla:
    grid_size: 0.01
    output_dim: 512
    enable_flash: true
discriminator:
  checkpoint: null
  checkpoint_object_encoder_pretrained: null
  object_backbone: pointnet
  gripper_backbone: z_offset
  pointnet_version: v1
  num_embed_dim: 256
  num_object_dim: 512
  num_gripper_dim: 512
  grasp_repr: r3_6d
  pose_repr: mlp
  topk_ratio: 0.75
  kappa: 1.0
  ptv3:
    grid_size: 0.01
  ptv3vanilla:
    grid_size: 0.01
    output_dim: 512
    enable_flash: false
  warpptv3:
    voxel_size: 0.01
    enc_depths:
    - 2
    - 2
    - 2
    - 6
    - 2
    enc_channels:
    - 32
    - 64
    - 128
    - 256
    - 512
    enc_num_head:
    - 2
    - 4
    - 8
    - 16
    - 32
    enc_patch_size:
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
    mlp_ratio: 4
    drop_path: 0.3
    drop_path_schedule: constant
optimizer:
  type: ADAMW
  base_batch_size: 128
  base_lr: 0.0008
  backbone_multiplier: 1.0
  grad_clip: -1
  weight_decay: 0.05
  lr_scale_multiplier: 1.0
  lr: 1.0e-05
  momentum: 0.9
train:
  model_name: diffusion
  num_gpus: 16
  port: 17423
  mask_thresh: 0.5
  batch_size: 32
  num_workers: 1
  num_epochs: 6000
  print_freq: 20
  plot_freq: 20
  save_freq: 32
  eval_freq: 10
  checkpoint: /tmp
  log_dir: /tmp
  num_scenes: null
  debug: false
  debug_ddp: false
  train_obj_split: train_xgrasp_v2
  valid_obj_split: valid_dev
  train_gripper_split: proc_v1_train_32
  valid_gripper_split: valid_gripper
  train_grasp_split: train_graspgenX
  valid_grasp_split: valid_graspgenX
eval:
  model_name: diffusion
  task: pick
  obj_split: valid_small
  gripper_split: valid_gripper
  grasp_split: null
  first_scene: -1
  last_scene: 1000
  scene: null
  gen_checkpoint: ''
  dis_checkpoint: ''
  output_dir: null
  exp_name: null
  cam_coord: false
  object_thresh: 0.2
  mask_thresh: 0.2
  seed_thresh: null
  num_seed_grasps: 150
  max_num_grasps: 200
  retract: 0.0
  grid_res: 0.01
  placement_height: 0.02
  placement_vis_radius: 0.2
  batch_size: 4
  num_workers: 1
  print_freq: 1
  num_procs: 1
  num_vis: 5
  num_runs: 1
  debug: true
  scene_file: ''
  output_file: ''
  write_output_file: true
  grasp_seeder: false
  config_save_file: /tmp
  color_grasp_with_conf: false
  max_grasps_per_chunk: 100
  single_gripper: null
  max_eval_objects: -1
  missing_json: null
meshcat:
  visualize: true
  point_size: 0.01
  line_width: 2
run: train_mode
